name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v2

      - name: JavaScript Test & Coverage
        shell: bash -l {0}
        run: nvm install && yarn install && npx yarn run test:coverage

      - name: Python Test & Coverage
        run: pip3 install pytest pytest-cov && pytest src/__tests__ --cov=src --cov-report xml:cov.xml && pytest src --junitxml=exec.xml

  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v2

      - name: Pylint
        run: pip3 install pylint && pylint src --exit-zero --output-format=parseable > pylint.parseable

      - name: ESLint
        shell: bash -l {0}
        run: nvm install && yarn install eslint && yarn run eslint src -f json -o eslint.json

  Dependency_Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install node modules
        shell: bash -l {0}
        run: nvm install && yarn install
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: "sonar-source-test"
          path: "."
          format: "HTML"
          others: ""
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
          name: Depcheck report
          path: ${{github.workspace}}
